### ISSUE TITLE
how to run as daemon

### ISSUE THREAD

**Issue by transtone** [fiorix/go-eventsocket#3]
I user server.go example file, but when hungup a call, the program exit with this log:

New event
Content-Disposition: "disconnect"
Content-Length: "67"
Content-Type: "text/disconnect-notice"
Controlled-Session-Uuid: "34d4e991-50c8-4ad2-8a18-4b0fc573d1ba"
BODY: "Disconnected, goodbye.\nSee you at ClueCon! http://www.cluecon.com/\n"
2015/01/07 14:05:48 EOF
exit status 1

How can I keep it alive as a daemon?

**Comment by fiorix** [comment]
The server.go example is a demon that runs in foreground and calls the `handler` function for every incoming client. It only quits if you hit control-c.

It's not meant to be used in production but if what you're looking for is to run that in background (assuming you use Linux) you should use upstart or systemd to do so.

**Comment by transtone** [comment]
It only quits if you hit control-c.
==============
In my debian system, It quits on call hangup, and it get a event called "disconnect"

**Comment by fiorix** [comment]
The client does quit, because of this line: https://github.com/fiorix/go-eventsocket/blob/master/examples/client/client.go#L33

But the server does not. Like I said these are examples and if you want to make them proper daemons you will have to code it. The package does not offer any client/server besides these two examples.

**Comment by transtone** [comment]
server do quit with two lines after call hungup:
2015/01/08 14:05:48 EOF
exit status 1

It seems some error occued. 
I use debian-7.5-amd64/freeswitch-1.4.15/go-1.4  
with dialplan: <action application="socket" data="127.0.0.1:9090 sync full"/>

**Comment by transtone** [comment]
if not set the [playback_terminators](https://developer.signalwire.com/freeswitch/Channel-Variables-Catalog/playback_terminators_16353264/), when send the dtmf '*', it will terminator the palyback and cause the disconnection.

so disable it by
```golang
c.Execute("set", "playback_terminators=none", true)
```
